import { Component, OnInit } from '@angular/core';
import { AuthenticationService} from './../services/authentication.service';
import { AngularFirestore } from '@angular/fire/firestore';
import { Router } from '@angular/router';
import { UserService } from '../user.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.page.html',
  styleUrls: ['./home.page.scss'],
})
export class HomePage implements OnInit {

  constructor(
    private authService: AuthenticationService,
    public afStore: AngularFirestore,
    public router: Router,
    public user: UserService
    ) { 
      //this.currentuser = user.getcurretUID()
    }

  ngOnInit() {
  }
  
  createlobby() {
    // const newData = this.afStore.collection(`lobby`).add({
    // });
    this.router.navigate(['tabs/set-lobby']);
  }
  logout() {
    this.authService.logout();
  }
}

// // Generate a reference to a new location and add some data using push()
// var newPostRef = postsRef.push({
//   author: "gracehop",
//   title: "Announcing COBOL, a New Programming Language"
// });
// // Get the unique ID generated by push() by accessing its key
// var postID = newPostRef.key;
